maxerr: false
spec-char-escape: false
text-ignore-regex: false
raw-ignore-regex: false
attr-name-ignore-regex: false
id-class-ignore-regex: false
line-max-len-ignore-regex: false
rules:
  indent-width: false # за отступы отвечает editor-config и prettier
  tag-self-close:
    - true
    - "never"
  tag-name-lowercase: true
